In [1]:
# import packages

import pandas as pd
import numpy as np

In [46]:
data = pd.read_csv("Data.csv")

In [47]:
data.head(2)

Country   Age   Salary Purchased
0  France  44.0  72000.0        No
1   Spain  27.0  48000.0       Yes

In [40]:
x = data['Country']

In [48]:
type(data.iloc[:, 0])

pandas.core.series.Series

In [49]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()

data.iloc[:, 0] = labelencoder.fit_transform(data.iloc[:, 0])

In [50]:
data.head()

Country   Age   Salary Purchased
0        0  44.0  72000.0        No
1        2  27.0  48000.0       Yes
2        1  30.0  54000.0        No
3        2  38.0  61000.0        No
4        1  40.0      NaN       Yes

In [59]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features = [0])

output_data = data.iloc[:, 0].values
print (output_data),output_data.ndim

print type(output_data)
#Reshape dataset before apply fit_transform function
output_data = output_data.reshape(-1, 1) # To make it 2D

print (output_data),output_data.ndim

output_data = onehotencoder.fit_transform(output_data).toarray()

[0 2 1 2 1 0 2 0 1 0] 1
<type 'numpy.ndarray'>
[[0]
 [2]
 [1]
 [2]
 [1]
 [0]
 [2]
 [0]
 [1]
 [0]] 2


C:\Users\sachi\Anaconda2\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [55]:
output_data

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])